tcp_port = "8088"
http_port = "80"
max_conn = 10000
namespace = "n1"

[etcd_common]
  endpoints = ["11.24.102.245:2379", "11.24.102.246:2379", "11.24.17.250:2379"]
  dial_timeout = "5s"
  rw_timeout = "15s"
  retry_num = 2
  retry_interval = "2s"

[gateway]
  conn_num_per_backend = 5
  query_strategy = "masterfirst"
  [gateway.route]
    shard_group_ttl = "8784h"
    shard_group_tick_interval = "24h"
  [gateway.appender]
    async_transfer = true
  [gateway.query_engine]
    concurrency = 50
    timeout = "2m"

[storage]
  [storage.tsdb]
    path = "/tmp/tsdb"
    lookback_delta = "5s"
    retention_duration = "360h"
    block_ranges = [1800000, 3600000, 14400000, 28800000, 86400000]
    enable_wal = false
  [storage.stat_report]
    heartbeart_interval = "30s"
    session_expire_ttl = "30s"
  [storage.replication]
    handleoff_size = "256m"
    heartbeart_interval = "30s"

[jaeger]
  sampler_type = "ratelimiting"
  sample_num_per_sec = 10000
  agent_host_port = ""
  collector_endpoint = "http://xx.xx.com/api/traces"
