# let the baudtime run as the only role of gateway
tcp_port = "8088"
http_port = "80"
max_conn = 10000
namespace = "n1"
lookback_delta = "5s"

[etcd]
  endpoints = ["localhost:2379"]
  dial_timeout = "5s"
  rw_timeout = "15s"
  retry_num = 2
  retry_interval = "2s"

[gateway]
  read_conns_per_backend = 10
  write_conns_per_backend = 1
  query_strategy = "masterfirst"
  [gateway.route]
    shard_group_ttl = "8784h"
    shard_group_tick_interval = "24h"
  [gateway.appender]
    async_transfer = true
  [gateway.query_engine]
    concurrency = 50
    timeout = "2m"

[jaeger]
  sampler_type = "ratelimiting"
  sample_num_per_sec = 10000
  agent_host_port = ""
  collector_endpoint = "http://xx.xx.com/api/traces"
